### ISSUE TITLE
Select doesn't work inside of Dialog

### ISSUE THREAD

**Issue by alexkorep** [ClickHouse/click-ui#214]
### Steps to reproduce
- Place a `Select` inside a `Dialog`: 
```Typescript
    <Dialog open={open}>
      <Dialog.Content title="Dialog" data-testid="service-connect-modal">
        <Select
          value={'no value'}
          onSelect={(value): void => {
            alert(value);
          }}
        >
          <Select.Item value="item1">Item 1</Select.Item>
          <Select.Item value="item2">Item 2</Select.Item>
        </Select>
      </Dialog.Content>
    </Dialog>
```

- Show the dialog, try to select the item.

### Expected result
- the items have the hand icon and can be selected.

### Actual results
- the items cannot be selected.
- The items have CSS attribute `pointer-events: none;` inherited from `body`, because they exist outside of the Dialog HTML container.
- Video:

https://github.com/ClickHouse/click-ui/assets/1166594/d2815005-05f7-49df-9839-d845dc447e27

**Comment by vineethasok** [comment]
I have seen that the same issue is reported in radix-ui
https://github.com/radix-ui/primitives/issues/2121
Since we need to update the pointer events globally and since we don't have a global css in click-ui we might need to wait until they publish the fix
I'll comment on the ticket they posted for now
