### ISSUE TITLE
Add Badge for Primary card

### ISSUE THREAD

**Issue by mshustov** [ClickHouse/click-ui#393]
We'd like to have a `Badge`. The same as it's done for [Secondary card](https://click-ui.vercel.app/?path=/docs/cards-secondary-card--docs).
![2024-04-15_17-41-01](https://github.com/ClickHouse/click-ui/assets/3198181/ee55d719-d0f3-46e2-bd34-fddc385a7d55)

**Comment by gjones** [comment]
@mshustov @danielclickh Perhaps for consistency we should use [this style](https://github.com/ClickHouse/click-ui/pull/419) for the beta badge?

**Comment by danielclickh** [comment]
Hey @gjones ! That was actually intentional. The badge being offset outside the box didn't look great in a grid format, as items from one row were too close to the badge of the row below. So, I moved it inside the item. I understand the need for consistency, but maybe we can apply your suggestion inside the card?

**Comment by mshustov** [comment]
done in https://github.com/ClickHouse/click-ui/pull/430
